baseURL = 'https://brayd.blog/'
languageCode = 'en-us'
title = 'Brayd’s Blog'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[pagination]
  pagerSize = 10

[params]
  env = 'production'
  title = 'Brayd’s Blog'
  description = 'A blog about all things IT, Linux, veganism, martial arts and more!'
  keywords = ['Blog', 'Linux', 'IT', 'veganism', 'mma', 'muay thai']
  author = 'Brayd'
  DateFormat = 'January 2, 2006'
  defaultTheme = 'auto'
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[params.homeInfoParams]
  title = 'Brayd’s Blog 🌱'
  content = 'A blog about all things IT, Linux, veganism, martial arts and more!'

[[params.socialIcons]]
    name = 'mastodon'
    url = 'https://glitch.braydmedia.de/@brayd'

[[params.socialIcons]]
    name = 'bluesky'
    url = 'https://bsky.app/profile/did:plc:rwknrk4qp3xgy6kndprmrn4r'

[[params.socialIcons]]
    name = 'email'
    url = 'mailto:info@braydmedia.de'

[[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/br4yd'

[[params.socialIcons]]
    name = 'goodreads'
    url = 'https://www.goodreads.com/user/show/182168274-brayd'

[[params.socialIcons]]
    name = 'lastfm'
    url = 'https://www.last.fm/user/braydofficial'

[[params.socialIcons]]
    name = 'liberapay'
    url = 'https://liberapay.com/Braydofficial'

[[params.socialIcons]]
    name = 'matrix'
    url = 'https://matrix.to/#/@brayd:chat.braydsocial.eu'

[[params.socialIcons]]
    name = 'pgp'
    url = 'https://keys.openpgp.org/vks/v1/by-fingerprint/D3001046920B6E9CF23679ABC2B176B9DEB8BA48'

[[params.socialIcons]]
    name = 'rss'
    url = 'https://brayd.blog/posts/index.xml'

[params.editPost]
    URL = 'https://github.com/br4yd/braydblog/content'
    text = 'Suggest changes'
    appendFilePath = true

[params.social]
    fediverse_creator = '@brayd@glitch.braydmedia.de'

# ===================[ Menu ]===================
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 20

[[menu.main]]
identifier = "mastodon"
name = "Mastodon"
url = "https://glitch.braydmedia.de"
weight = 30
